// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/yandex_auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	YandexAuthService_GetYandexAuthURL_FullMethodName = "/proto.YandexAuthService/GetYandexAuthURL"
	YandexAuthService_ExchangeCode_FullMethodName     = "/proto.YandexAuthService/ExchangeCode"
)

// YandexAuthServiceClient is the client API for YandexAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YandexAuthServiceClient interface {
	GetYandexAuthURL(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*YandexAuthURLResponse, error)
	ExchangeCode(ctx context.Context, in *YandexCodeRequest, opts ...grpc.CallOption) (*YandexUserResponse, error)
}

type yandexAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYandexAuthServiceClient(cc grpc.ClientConnInterface) YandexAuthServiceClient {
	return &yandexAuthServiceClient{cc}
}

func (c *yandexAuthServiceClient) GetYandexAuthURL(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*YandexAuthURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YandexAuthURLResponse)
	err := c.cc.Invoke(ctx, YandexAuthService_GetYandexAuthURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yandexAuthServiceClient) ExchangeCode(ctx context.Context, in *YandexCodeRequest, opts ...grpc.CallOption) (*YandexUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YandexUserResponse)
	err := c.cc.Invoke(ctx, YandexAuthService_ExchangeCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YandexAuthServiceServer is the server API for YandexAuthService service.
// All implementations must embed UnimplementedYandexAuthServiceServer
// for forward compatibility.
type YandexAuthServiceServer interface {
	GetYandexAuthURL(context.Context, *Empty) (*YandexAuthURLResponse, error)
	ExchangeCode(context.Context, *YandexCodeRequest) (*YandexUserResponse, error)
	mustEmbedUnimplementedYandexAuthServiceServer()
}

// UnimplementedYandexAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedYandexAuthServiceServer struct{}

func (UnimplementedYandexAuthServiceServer) GetYandexAuthURL(context.Context, *Empty) (*YandexAuthURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetYandexAuthURL not implemented")
}
func (UnimplementedYandexAuthServiceServer) ExchangeCode(context.Context, *YandexCodeRequest) (*YandexUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeCode not implemented")
}
func (UnimplementedYandexAuthServiceServer) mustEmbedUnimplementedYandexAuthServiceServer() {}
func (UnimplementedYandexAuthServiceServer) testEmbeddedByValue()                           {}

// UnsafeYandexAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YandexAuthServiceServer will
// result in compilation errors.
type UnsafeYandexAuthServiceServer interface {
	mustEmbedUnimplementedYandexAuthServiceServer()
}

func RegisterYandexAuthServiceServer(s grpc.ServiceRegistrar, srv YandexAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedYandexAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&YandexAuthService_ServiceDesc, srv)
}

func _YandexAuthService_GetYandexAuthURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YandexAuthServiceServer).GetYandexAuthURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YandexAuthService_GetYandexAuthURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YandexAuthServiceServer).GetYandexAuthURL(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _YandexAuthService_ExchangeCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YandexCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YandexAuthServiceServer).ExchangeCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YandexAuthService_ExchangeCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YandexAuthServiceServer).ExchangeCode(ctx, req.(*YandexCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YandexAuthService_ServiceDesc is the grpc.ServiceDesc for YandexAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YandexAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.YandexAuthService",
	HandlerType: (*YandexAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetYandexAuthURL",
			Handler:    _YandexAuthService_GetYandexAuthURL_Handler,
		},
		{
			MethodName: "ExchangeCode",
			Handler:    _YandexAuthService_ExchangeCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/yandex_auth.proto",
}
