// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/yandex_auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_yandex_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yandex_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_yandex_auth_proto_rawDescGZIP(), []int{0}
}

type YandexAuthURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YandexAuthURLResponse) Reset() {
	*x = YandexAuthURLResponse{}
	mi := &file_proto_yandex_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YandexAuthURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YandexAuthURLResponse) ProtoMessage() {}

func (x *YandexAuthURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yandex_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YandexAuthURLResponse.ProtoReflect.Descriptor instead.
func (*YandexAuthURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_yandex_auth_proto_rawDescGZIP(), []int{1}
}

func (x *YandexAuthURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type YandexCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YandexCodeRequest) Reset() {
	*x = YandexCodeRequest{}
	mi := &file_proto_yandex_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YandexCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YandexCodeRequest) ProtoMessage() {}

func (x *YandexCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yandex_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YandexCodeRequest.ProtoReflect.Descriptor instead.
func (*YandexCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_yandex_auth_proto_rawDescGZIP(), []int{2}
}

func (x *YandexCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type YandexUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=Login,proto3" json:"Login,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YandexUserResponse) Reset() {
	*x = YandexUserResponse{}
	mi := &file_proto_yandex_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YandexUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YandexUserResponse) ProtoMessage() {}

func (x *YandexUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yandex_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YandexUserResponse.ProtoReflect.Descriptor instead.
func (*YandexUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_yandex_auth_proto_rawDescGZIP(), []int{3}
}

func (x *YandexUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *YandexUserResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *YandexUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_yandex_auth_proto protoreflect.FileDescriptor

const file_proto_yandex_auth_proto_rawDesc = "" +
	"\n" +
	"\x17proto/yandex_auth.proto\x12\x05proto\"\a\n" +
	"\x05Empty\")\n" +
	"\x15YandexAuthURLResponse\x12\x10\n" +
	"\x03Url\x18\x01 \x01(\tR\x03Url\"'\n" +
	"\x11YandexCodeRequest\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\"P\n" +
	"\x12YandexUserResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x14\n" +
	"\x05Login\x18\x02 \x01(\tR\x05Login\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email2\x98\x01\n" +
	"\x11YandexAuthService\x12>\n" +
	"\x10GetYandexAuthURL\x12\f.proto.Empty\x1a\x1c.proto.YandexAuthURLResponse\x12C\n" +
	"\fExchangeCode\x12\x18.proto.YandexCodeRequest\x1a\x19.proto.YandexUserResponseB\x0eZ\f/proto;protob\x06proto3"

var (
	file_proto_yandex_auth_proto_rawDescOnce sync.Once
	file_proto_yandex_auth_proto_rawDescData []byte
)

func file_proto_yandex_auth_proto_rawDescGZIP() []byte {
	file_proto_yandex_auth_proto_rawDescOnce.Do(func() {
		file_proto_yandex_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_yandex_auth_proto_rawDesc), len(file_proto_yandex_auth_proto_rawDesc)))
	})
	return file_proto_yandex_auth_proto_rawDescData
}

var file_proto_yandex_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_yandex_auth_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: proto.Empty
	(*YandexAuthURLResponse)(nil), // 1: proto.YandexAuthURLResponse
	(*YandexCodeRequest)(nil),     // 2: proto.YandexCodeRequest
	(*YandexUserResponse)(nil),    // 3: proto.YandexUserResponse
}
var file_proto_yandex_auth_proto_depIdxs = []int32{
	0, // 0: proto.YandexAuthService.GetYandexAuthURL:input_type -> proto.Empty
	2, // 1: proto.YandexAuthService.ExchangeCode:input_type -> proto.YandexCodeRequest
	1, // 2: proto.YandexAuthService.GetYandexAuthURL:output_type -> proto.YandexAuthURLResponse
	3, // 3: proto.YandexAuthService.ExchangeCode:output_type -> proto.YandexUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_yandex_auth_proto_init() }
func file_proto_yandex_auth_proto_init() {
	if File_proto_yandex_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_yandex_auth_proto_rawDesc), len(file_proto_yandex_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_yandex_auth_proto_goTypes,
		DependencyIndexes: file_proto_yandex_auth_proto_depIdxs,
		MessageInfos:      file_proto_yandex_auth_proto_msgTypes,
	}.Build()
	File_proto_yandex_auth_proto = out.File
	file_proto_yandex_auth_proto_goTypes = nil
	file_proto_yandex_auth_proto_depIdxs = nil
}
