// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RyazanTrip.DataAccess.Postgres;

#nullable disable

namespace RyazanTrip.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(RyazanTripDbContext))]
    partial class RyazanTripDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.BonusEntity", b =>
                {
                    b.Property<int>("BonusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BonusId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<short?>("DiscountPercent")
                        .HasColumnType("smallint");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("BonusId");

                    b.ToTable("bonuses", (string)null);
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.ImageEntity", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("ImageId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.LevelEntity", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("RequiredExp")
                        .HasColumnType("integer");

                    b.HasKey("LevelId");

                    b.ToTable("levels", (string)null);

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            Name = "Медь",
                            RequiredExp = 0
                        },
                        new
                        {
                            LevelId = 2,
                            Name = "Железо",
                            RequiredExp = 100
                        },
                        new
                        {
                            LevelId = 3,
                            Name = "Золото",
                            RequiredExp = 500
                        },
                        new
                        {
                            LevelId = 4,
                            Name = "Платина",
                            RequiredExp = 1000
                        },
                        new
                        {
                            LevelId = 5,
                            Name = "Брилиант",
                            RequiredExp = 5000
                        });
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.MushroomEntity", b =>
                {
                    b.Property<int>("MushroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MushroomId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("MushroomId");

                    b.HasIndex("ImageId");

                    b.ToTable("mushrooms", (string)null);
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.MushroomSubmissionEntity", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubmissionId"));

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer");

                    b.Property<int?>("MushroomId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SubmissionId");

                    b.HasIndex("ImageId");

                    b.HasIndex("MushroomId");

                    b.HasIndex("UserId");

                    b.ToTable("mushroom_submissions", (string)null);
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.PaymentEntity", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("UserTourId")
                        .HasColumnType("integer");

                    b.Property<string>("YukassaPaymentId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("PaymentId");

                    b.HasIndex("UserTourId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.RoleEntity", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("RoleId");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.SessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.TourEntity", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TourId"));

                    b.Property<string>("Coords")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<TimeSpan>("TourTime")
                        .HasColumnType("time");

                    b.HasKey("TourId");

                    b.HasIndex("ImageId");

                    b.HasIndex("Price");

                    b.HasIndex("Title");

                    b.HasIndex("TourTime");

                    b.HasIndex("Title", "TourTime")
                        .IsUnique();

                    b.ToTable("tours", (string)null);
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.UserBonusEntity", b =>
                {
                    b.Property<int>("UserBonusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserBonusId"));

                    b.Property<int?>("BonusId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserBonusId");

                    b.HasIndex("BonusId");

                    b.HasIndex("UserId");

                    b.ToTable("user_bonuses", (string)null);
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int?>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "artpupser@ya.ru",
                            Experience = 0,
                            LevelId = 1,
                            PasswordHash = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            RoleId = 2,
                            Town = "Рязань",
                            Username = "artpupser"
                        });
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.UserTourEntity", b =>
                {
                    b.Property<int>("UserTourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTourId"));

                    b.Property<string>("GuideOption")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("TourId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserTourId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("user_tours", (string)null);
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.MushroomEntity", b =>
                {
                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.ImageEntity", "Image")
                        .WithMany("Mushrooms")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.MushroomSubmissionEntity", b =>
                {
                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.ImageEntity", "Image")
                        .WithMany("Submissions")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.MushroomEntity", "Mushroom")
                        .WithMany("Submissions")
                        .HasForeignKey("MushroomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.UserEntity", "User")
                        .WithMany("MushroomSubmissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Image");

                    b.Navigation("Mushroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.PaymentEntity", b =>
                {
                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.UserTourEntity", "UserTour")
                        .WithMany("Payments")
                        .HasForeignKey("UserTourId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserTour");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.SessionEntity", b =>
                {
                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.UserEntity", "UserEntity")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.TourEntity", b =>
                {
                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.ImageEntity", "ImageEntity")
                        .WithMany("Tours")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImageEntity");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.UserBonusEntity", b =>
                {
                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.BonusEntity", "Bonus")
                        .WithMany("UserBonuses")
                        .HasForeignKey("BonusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.UserEntity", "User")
                        .WithMany("UserBonuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bonus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.UserEntity", b =>
                {
                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.LevelEntity", "LevelEntity")
                        .WithMany("Users")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.RoleEntity", "RoleEntity")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LevelEntity");

                    b.Navigation("RoleEntity");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.UserTourEntity", b =>
                {
                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.TourEntity", "TourEntity")
                        .WithMany("UserTours")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RyazanTrip.DataAccess.Postgres.Entities.UserEntity", "UserEntity")
                        .WithMany("UserTours")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.BonusEntity", b =>
                {
                    b.Navigation("UserBonuses");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.ImageEntity", b =>
                {
                    b.Navigation("Mushrooms");

                    b.Navigation("Submissions");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.LevelEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.MushroomEntity", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.TourEntity", b =>
                {
                    b.Navigation("UserTours");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.UserEntity", b =>
                {
                    b.Navigation("MushroomSubmissions");

                    b.Navigation("Sessions");

                    b.Navigation("UserBonuses");

                    b.Navigation("UserTours");
                });

            modelBuilder.Entity("RyazanTrip.DataAccess.Postgres.Entities.UserTourEntity", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
